In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('20240617-DE-TS-LectureMaterials/Python/Data/imdb_top_1000.csv')

In [3]:
nf =df.drop(["Poster_Link","Certificate","No_of_Votes","Meta_score",'Runtime'], axis="columns")
nf

,Series_Title,Released_Year,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,Gross
0,The Shawshank Redemption,1994,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469"
1,The Godfather,1972,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411"
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444"
3,The Godfather: Part II,1974,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"57,300,000"
4,12 Angry Men,1957,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,NaN
996,Giant,1956,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,NaN
997,From Here to Eternity,1953,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,"30,500,000"
998,Lifeboat,1944,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,NaN
999,The 39 Steps,1935,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,NaN

In [4]:
year = nf[pd.to_numeric(nf['Released_Year'],errors='coerce').notnull()]
oldest = year.sort_values(by=['Released_Year'])
oldest.head(1)

,Series_Title,Released_Year,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,Gross
321,Das Cabinet des Dr. Caligari,1920,"Fantasy, Horror, Mystery",8.1,"Hypnotist Dr. Caligari uses a somnambulist, Ce...",Robert Wiene,Werner Krauss,Conrad Veidt,Friedrich Feher,Lil Dagover,NaN

In [5]:
newest = year.sort_values(by=['Released_Year'],ascending=False)
newest.head(1)

,Series_Title,Released_Year,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,Gross
613,Druk,2020,"Comedy, Drama",7.8,"Four friends, all high school teachers, test a...",Thomas Vinterberg,Mads Mikkelsen,Thomas Bo Larsen,Magnus Millang,Lars Ranthe,NaN

In [6]:
rate=nf.sort_values(by=['IMDB_Rating'],ascending=False)
rate.head(10)

,Series_Title,Released_Year,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,Gross
0,The Shawshank Redemption,1994,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469"
1,The Godfather,1972,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411"
4,12 Angry Men,1957,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"4,360,000"
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444"
3,The Godfather: Part II,1974,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"57,300,000"
5,The Lord of the Rings: The Return of the King,2003,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,"377,845,905"
7,Schindler's List,1993,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,"96,898,818"
6,Pulp Fiction,1994,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,"107,928,762"
8,Inception,2010,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,"292,576,195"
12,"Il buono, il brutto, il cattivo",1966,Western,8.8,A bounty hunting scam joins two men in an unea...,Sergio Leone,Clint Eastwood,Eli Wallach,Lee Van Cleef,Aldo GiuffrÃ¨,"6,100,000"

In [7]:
nf2=nf.copy()
nf2['Genres']= nf2['Genre'].str.split(', ').tolist()
nf2=nf2.explode('Genres')
genres= nf2.sort_values(by=['IMDB_Rating'],ascending=False)
genreTop=genres.drop_duplicates(subset=['Genres'], keep='first')
genreBest=genreTop.drop_duplicates(subset=['Series_Title'], keep='first')
genreBest.head(20)

,Series_Title,Released_Year,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,Gross,Genres
0,The Shawshank Redemption,1994,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469",Drama
1,The Godfather,1972,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411",Crime
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444",Action
7,Schindler's List,1993,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,"96,898,818",History
5,The Lord of the Rings: The Return of the King,2003,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,"377,845,905",Adventure
11,Forrest Gump,1994,"Drama, Romance",8.8,"The presidencies of Kennedy and Johnson, the e...",Robert Zemeckis,Tom Hanks,Robin Wright,Gary Sinise,Sally Field,"330,252,182",Romance
12,"Il buono, il brutto, il cattivo",1966,Western,8.8,A bounty hunting scam joins two men in an unea...,Sergio Leone,Clint Eastwood,Eli Wallach,Lee Van Cleef,Aldo GiuffrÃ¨,"6,100,000",Western
8,Inception,2010,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,"292,576,195",Sci-Fi
16,Star Wars: Episode V - The Empire Strikes Back,1980,"Action, Adventure, Fantasy",8.7,After the Rebels are brutally overpowered by t...,Irvin Kershner,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,"290,475,067",Fantasy
23,Sen to Chihiro no kamikakushi,2001,"Animation, Adventure, Family",8.6,"During her family's move to the suburbs, a sul...",Hayao Miyazaki,Daveigh Chase,Suzanne Pleshette,Miyu Irino,Rumi Hiiragi,"10,055,859",Animation
26,La vita Ã¨ bella,1997,"Comedy, Drama, Romance",8.6,When an open-minded Jewish librarian and his s...,Roberto Benigni,Roberto Benigni,Nicoletta Braschi,Giorgio Cantarini,Giustino Durano,"57,598,247",Comedy
27,Se7en,1995,"Crime, Drama, Mystery",8.6,"Two detectives, a rookie and a veteran, hunt a...",David Fincher,Morgan Freeman,Brad Pitt,Kevin Spacey,Andrew Kevin Walker,"100,125,643",Mystery
19,Gisaengchung,2019,"Comedy, Drama, Thriller",8.6,Greed and class discrimination threaten the ne...,Bong Joon Ho,Kang-ho Song,Lee Sun-kyun,Cho Yeo-jeong,Choi Woo-sik,"53,367,844",Thriller
32,It's a Wonderful Life,1946,"Drama, Family, Fantasy",8.6,An angel is sent from Heaven to help a despera...,Frank Capra,James Stewart,Donna Reed,Lionel Barrymore,Thomas Mitchell,NaN,Family
24,Saving Private Ryan,1998,"Drama, War",8.6,"Following the Normandy Landings, a group of U....",Steven Spielberg,Tom Hanks,Matt Damon,Tom Sizemore,Edward Burns,"216,540,909",War
34,Whiplash,2014,"Drama, Music",8.5,A promising young drummer enrolls at a cut-thr...,Damien Chazelle,Miles Teller,J.K. Simmons,Melissa Benoist,Paul Reiser,"13,092,000",Music
49,Psycho,1960,"Horror, Mystery, Thriller",8.5,"A Phoenix secretary embezzles $40,000 from her...",Alfred Hitchcock,Anthony Perkins,Janet Leigh,Vera Miles,John Gavin,"32,000,000",Horror
82,Sunset Blvd.,1950,"Drama, Film-Noir",8.4,A screenwriter develops a dangerous relationsh...,Billy Wilder,William Holden,Gloria Swanson,Erich von Stroheim,Nancy Olson,NaN,Film-Noir
76,Anand,1971,"Drama, Musical",8.4,The story of a terminally ill man who wishes t...,Hrishikesh Mukherjee,Rajesh Khanna,Amitabh Bachchan,Sumita Sanyal,Ramesh Deo,NaN,Musical
100,Bacheha-Ye aseman,1997,"Drama, Family, Sport",8.3,"After a boy loses his sister's pair of shoes, ...",Majid Majidi,Mohammad Amir Naji,Amir Farrokh Hashemian,Bahare Seddiqi,Nafise Jafar-Mohammadi,"933,933",Sport

In [8]:
director=nf.value_counts('Director')
director.head(1)

Director
Alfred Hitchcock    14
Name: count, dtype: int64

In [9]:
actors1=nf.copy()
actors1['Stars']=actors1[['Star1','Star2','Star3','Star4']].values.tolist()
actors2=actors1.explode('Stars')
stars=actors2.value_counts('Stars')
stars.head(1)

Stars
Robert De Niro    17
Name: count, dtype: int64

In [28]:
nf3=nf2.copy()
nf3=nf3.dropna(subset=['Gross'])
nf3['Gross'] = nf3.Gross.str.split(',').str.join('').astype(int)
nf3.head()

,Series_Title,Released_Year,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,Gross,Genres
0,The Shawshank Redemption,1994,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,28341469,Drama
1,The Godfather,1972,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,134966411,Crime
1,The Godfather,1972,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,134966411,Drama
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,534858444,Action
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,534858444,Crime

In [30]:
nf4=nf3.copy()
nf4=nf3.dropna(subset=['Gross'])
genresGross= nf4.sort_values(by=['Gross'],ascending=False)
genresGross1=genresGross.drop_duplicates(subset=['Genres'], keep='first')
genresGross2=genresGross1.drop_duplicates(subset=['Series_Title'], keep='first')
genresGross2.head(25)

,Series_Title,Released_Year,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,Gross,Genres
477,Star Wars: Episode VII - The Force Awakens,2015,"Action, Adventure, Sci-Fi",7.9,"As a new threat to the galaxy rises, Rey, a de...",J.J. Abrams,Daisy Ridley,John Boyega,Oscar Isaac,Domhnall Gleeson,936662225,Sci-Fi
59,Avengers: Endgame,2019,"Action, Adventure, Drama",8.4,After the devastating events of Avengers: Infi...,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Evans,Mark Ruffalo,858373000,Drama
623,Avatar,2009,"Action, Adventure, Fantasy",7.8,A paraplegic Marine dispatched to the moon Pan...,James Cameron,Sam Worthington,Zoe Saldana,Sigourney Weaver,Michelle Rodriguez,760507625,Fantasy
652,Titanic,1997,"Drama, Romance",7.8,A seventeen-year-old aristocrat falls in love ...,James Cameron,Leonardo DiCaprio,Kate Winslet,Billy Zane,Kathy Bates,659325379,Romance
891,Incredibles 2,2018,"Animation, Action, Adventure",7.6,The Incredibles family takes on a new mission ...,Brad Bird,Craig T. Nelson,Holly Hunter,Sarah Vowell,Huck Milner,608581744,Animation
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,534858444,Crime
688,E.T. the Extra-Terrestrial,1982,"Family, Sci-Fi",7.8,A troubled child summons the courage to help a...,Steven Spielberg,Henry Thomas,Drew Barrymore,Peter Coyote,Dee Wallace,435110554,Family
596,Toy Story 4,2019,"Animation, Adventure, Comedy",7.8,"When a new toy called ""Forky"" joins Woody and ...",Josh Cooley,Tom Hanks,Tim Allen,Annie Potts,Tony Hale,434038008,Comedy
33,Joker,2019,"Crime, Drama, Thriller",8.5,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,Joaquin Phoenix,Robert De Niro,Zazie Beetz,Frances Conroy,335451311,Thriller
248,The Sixth Sense,1999,"Drama, Mystery, Thriller",8.1,A boy who communicates with spirits seeks the ...,M. Night Shyamalan,Bruce Willis,Haley Joel Osment,Toni Collette,Olivia Williams,293506292,Mystery
915,The Blind Side,2009,"Biography, Drama, Sport",7.6,"The story of Michael Oher, a homeless and trau...",John Lee Hancock,Quinton Aaron,Sandra Bullock,Tim McGraw,Jae Head,255959475,Sport
419,The Exorcist,1973,Horror,8.0,When a 12-year-old girl is possessed by a myst...,William Friedkin,Ellen Burstyn,Max von Sydow,Linda Blair,Lee J. Cobb,232906145,Horror
24,Saving Private Ryan,1998,"Drama, War",8.6,"Following the Normandy Landings, a group of U....",Steven Spielberg,Tom Hanks,Matt Damon,Tom Sizemore,Edward Burns,216540909,War
342,Bohemian Rhapsody,2018,"Biography, Drama, Music",8.0,The story of the legendary British rock band Q...,Bryan Singer,Rami Malek,Lucy Boynton,Gwilym Lee,Ben Hardy,216428042,Music
314,Gone with the Wind,1939,"Drama, History, Romance",8.1,A manipulative woman and a roguish man conduct...,Victor Fleming,George Cukor,Sam Wood,Clark Gable,Vivien Leigh,198676459,History
402,Dances with Wolves,1990,"Adventure, Drama, Western",8.0,"Lieutenant John Dunbar, assigned to a remote w...",Kevin Costner,Kevin Costner,Mary McDonnell,Graham Greene,Rodney A. Grant,184208848,Western
422,Fiddler on the Roof,1971,"Drama, Family, Musical",8.0,"In prerevolutionary Russia, a Jewish peasant c...",Norman Jewison,Topol,Norma Crane,Leonard Frey,Molly Picon,80500000,Musical
559,Notorious,1946,"Drama, Film-Noir, Romance",7.9,A woman is asked to spy on a group of Nazi fri...,Alfred Hitchcock,Cary Grant,Ingrid Bergman,Claude Rains,Louis Calhern,10464000,Film-Noir

In [31]:
directorGross=nf4.sort_values(by=['Gross'])
directors=directorGross.drop_duplicates(subset=['Director'],keep='first')
directors.head(10)

,Series_Title,Released_Year,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,Gross,Genres
630,Adams Ã¦bler,2005,"Comedy, Crime, Drama",7.8,A neo-nazi sentenced to community service at a...,Anders Thomas Jensen,Ulrich Thomsen,Mads Mikkelsen,Nicolas Bro,Paprika Steen,1305,Comedy
390,Knockin' on Heaven's Door,1997,"Action, Crime, Comedy",8.0,Two terminally ill patients escape from a hosp...,Thomas Jahn,Til Schweiger,Jan Josef Liefers,Thierry van Werveke,Moritz Bleibtreu,3296,Action
624,Mr. Nobody,2009,"Drama, Fantasy, Romance",7.8,A boy stands on a station platform as a train ...,Jaco Van Dormael,Jared Leto,Sarah Polley,Diane Kruger,Linh Dan Pham,3600,Drama
926,Dead Man's Shoes,2004,"Crime, Drama, Thriller",7.6,A disaffected soldier returns to his hometown ...,Shane Meadows,Paddy Considine,Gary Stretch,Toby Kebbell,Stuart Wolfenden,6013,Thriller
605,Ajeossi,2010,"Action, Crime, Drama",7.8,A quiet pawnshop keeper with a violent past ta...,Jeong-beom Lee,Won Bin,Sae-ron Kim,Tae-hoon Kim,Hee-won Kim,6460,Action
141,Udaan,2010,Drama,8.2,"Expelled from his school, a 16-year old boy re...",Vikramaditya Motwane,Rajat Barmecha,Ronit Roy,Manjot Singh,Ram Kapoor,7461,Drama
356,Tropa de Elite,2007,"Action, Crime, Drama",8.0,"In 1997 Rio de Janeiro, Captain Nascimento has...",JosÃ© Padilha,Wagner Moura,AndrÃ© Ramiro,Caio Junqueira,Milhem Cortaz,8060,Action
190,All About Eve,1950,Drama,8.2,A seemingly timid but secretly ruthless ingÃ©nu...,Joseph L. Mankiewicz,Bette Davis,Anne Baxter,George Sanders,Celeste Holm,10177,Drama
350,Dev.D,2009,"Drama, Romance",8.0,After breaking up with his childhood sweethear...,Anurag Kashyap,Abhay Deol,Mahie Gill,Kalki Koechlin,Dibyendu Bhattacharya,10950,Drama
187,Dial M for Murder,1954,"Crime, Thriller",8.2,A former tennis player tries to arrange his wi...,Alfred Hitchcock,Ray Milland,Grace Kelly,Robert Cummings,John Williams,12562,Crime

In [32]:
nf.to_parquet('nf.parquet')

In [35]:
nfSum=nf.copy()
nfSum['Gross']=nfSum['Gross'].fillna('0')
nfSum['Gross'] = nfSum.Gross.str.split(',').str.join('').astype(int)
nfSum=nfSum.dropna(subset=['Gross'])
sum=nfSum['Gross'].sum()
print(sum)

56536877976